apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: mangobutter/mangoboss-app:e7aac66
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mangoboss-config
            - secretRef:
                name: mangoboss-secret
          env:
            - name: TZ
              value: Asia/Seoul