apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: batch
          image: mangobutter/mangoboss-admin:6c20f0a
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mangoboss-config
            - secretRef:
                name: mangoboss-secret
          env:
            - name: TZ
              value: Asia/Seoul
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"