apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: admin.api.mangoboss.store
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 80