apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch
  labels:
    app: batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
        - name: batch
          image: mangobutter/mangoboss-batch:ce97961
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mangoboss-config
            - secretRef:
                name: mangoboss-secret
          env:
            - name: TZ
              value: Asia/Seoul