apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch
  labels:
    app: batch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
        - name: batch
          image: mangobutter/mangoboss-batch:331e745
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: mangoboss-config
            - secretRef:
                name: mangoboss-secret
          env:
            - name: TZ
              value: Asia/Seoul
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "1000m"